try{;(function(){var aC=window._vwo_code;if(aC){window._vwo_j_e=window._vwo_j_e||0;if(window._vwo_j_e==1){window._vwo_mt="dupCode";clearTimeout(window._vwo_settings_timer);if(window.VWO&&window.VWO._&&window.VWO._.bIE){window._vwo_code.finish()}return}if(window._vwo_j_e==-1){window._vwo_j_e=1}}window._vwo_mt="live";try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=window.location.search.match("_vwo_m=([^&]*)");n=n&&n[1]}return n&&JSON.parse(decodeURIComponent(n))};if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||getMode("_vwo_cc")||window.name.indexOf("_vis_preview")>-1){window._vwo_mt=window.name}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}if(window._vwo_mt!=="live"){if(!getMode("_vwo_cc")){_vwo_code.load('https://dev.visualwebsiteoptimizer.com/j.php?mode=' + encodeURIComponent(window._vwo_mt) + '&a=569996&f=1&u=' + encodeURIComponent(window._vis_opt_url||document.URL));}else{(function(){window._vwo_code&&window._vwo_code.finish();_vwo_ccc={u:"/j.php?a=569996&u=https%3A%2F%2Fpromo.libertex.org%2Flp%2Fes-lm%2Fcryptominer%2F%3Futm_id%3D4iQ7%26utm_campaign%3Dminer2%26utm_source%3Dbrave_libertex%26utm_content%3Dads%26utm_medium%3Dmedia%26utm_country%3Dlm&r=0.9533205586066669"};var s=document.createElement("script");s.src="https://app.vwo.com/visitor-behavior-analysis/dist/codechecker/cc.min.js?r="+Math.random();document.head.appendChild(s)})()}}}catch(e){var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3));aC&&window._vwo_code.finish()}})();if(window._vwo_mt==='live'){;window.VWO = window.VWO || []; window.VWO.push(['modifyClickPauseTime', { time: 0 }]);_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z){function f(a,b,d){e.cookie=a+"="+b+"; expires="+new Date(864e5*d+ +new Date).toGMTString()+"; domain="+c+"; path=/"}-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")&&(a=e.cookie.replace(/(?:(?:^|.*;\s*)_vwo_uuid_v2\s*=\s*([^;]*).*$)|^.*$/,"$1")||a,a=a.split("|"),b=new Image,c=d.location.hostname.replace(/^www\./,"")||c,b.src="https://dev.visualwebsiteoptimizer.com/v.gif?cd="+(window._vis_opt_cookieDays||0)+"&a=569996&d="+encodeURIComponent(c)+"&u="+a[0]+"&h="+a[1]+"&t="+z+"&r="+Math.random(),d.vwo_iehack_queue=[b],f("_vwo_uuid_v2",a.join("|"),366))})("libertex.org","DBBD3C59E9130ED99338E3FAC7AF02321|72a1563e099a210ac9e65a1a34f4b4fe",document,window,0,_vwo_code.sT);var _vwo_acc_id=569996;
clearTimeout(_vwo_settings_timer);_vwo_exp_ids=[],_vwo_exp={};window.VWO=window.VWO||[];
window.VWO.data={"noSS":false,"ts":1664808159};window.VWO.featureInfo={};var vwoCode = window._vwo_code; if(vwoCode.filterConfig && vwoCode.filterConfig.filterTime==='balanced'){ vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay() };var _vwo_style=document.getElementById('_vis_opt_path_hides'),_vwo_css= window._vwo_el_style || '{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;} :root {--vwo-el-opacity:0 !important;--vwo-el-filter:alpha(opacity=0) !important;--vwo-el-bg:none !important;}';
if(_vwo_style){_vwo_style.parentNode.removeChild(_vwo_style);}var commonWrapper=function(argument){if(!argument){argument={valuesGetter:function(){return{}},valuesSetter:function(){},verifyData:function(){return{}}}}var pollInterval=100;var timeout=5e3;return function(){var accountIntegrationSettings={};var _interval=null;function waitForAnalyticsVariables(){try{accountIntegrationSettings=argument.valuesGetter()}catch(error){accountIntegrationSettings=undefined}if(accountIntegrationSettings&&argument.verifyData(accountIntegrationSettings)){argument.valuesSetter(accountIntegrationSettings);return 1}return 0}var currentTime=0;_interval=setInterval((function(){currentTime=currentTime||performance.now();var result=waitForAnalyticsVariables();if(result||performance.now()-currentTime>=timeout){clearInterval(_interval)}}),pollInterval)}};
        var pushBasedCommonWrapper=function(argument){if(!argument){arguments={getExperimentList:function(){},pushData:function(){}}}return function(){window.VWO=window.VWO||[];window.VWO.push(["onVariationApplied",function(data){if(!data)return;var expId=data[1],variationId=data[2];var experimentList=argument.getExperimentList();if(expId&&variationId&&["VISUAL_AB","VISUAL","SPLIT_URL"].indexOf(_vwo_exp[expId].type)>-1){if(experimentList.indexOf(+expId)!==-1){var pollInterval=100;var currentTime=0;var timeout=5e3;var interval=setInterval((function(){currentTime=currentTime||performance.now();var toClearInterval=argument.pushData(expId,variationId);if(toClearInterval||performance.now()-currentTime>=timeout){clearInterval(interval)}}),pollInterval||100)}}}])}};
        (function(){var VWOOmniTemp={};window.VWOOmni=window.VWOOmni||{};                    for (var key in VWOOmniTemp) {
                        window.VWOOmni[key] = VWOOmniTemp[key];
                    }
                ;})();    (function(){window.VWO=window.VWO||[];var pollInterval=100;
        var _vis_data={};
        var intervalObj={};
        var analyticsTimerObj={};
        var experimentListObj={};window.VWO.push(["onVariationApplied",function(data){if(!data){return}var expId=data[1],variationId=data[2];if(expId&&variationId&&["VISUAL_AB","VISUAL","SPLIT_URL"].indexOf(window._vwo_exp[expId].type)>-1){}}])})();
    window.VWO.data.vi = window.VWO.data.vi || {"br":"Chrome","os":"Windows","de":"Other","dt":"desktop"};
window.VWO.push(['enableSPA']);
VWO.load_co=function(a){var b=document.createElement('script');b.src=a;b.crossOrigin='anonymous';b.fetchPriority='high';b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};document.getElementsByTagName('head')[0].appendChild(b);}
var _vwo_cookieDomain = 'libertex.org', _vwo_uuid = 'DBBD3C59E9130ED99338E3FAC7AF02321';window.VWO.data.as = "r2.visualwebsiteoptimizer.com";var _vwo_library_timer = setTimeout(function () { var vwoCode = window._vwo_code; vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay(); vwoCode.finish()},_vwo_code.library_tolerance());var _vis_opt_file = 'web/djIkdGU6Ny4wOmFzeW5jJWdxdWVyeQ==/tag-90d1c59b328d9c90a45785e87c70a86f.js',_vis_opt_lib = (typeof _vis_opt_lib=='undefined')?'https://dev.visualwebsiteoptimizer.com/'+_vis_opt_file:_vis_opt_lib;VWO.load_co(_vis_opt_lib);;window.VWO=window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};; 
window.VWO = window.VWO || [];
window.VWO.data = window.VWO.data || {};
VWO.data.content={"fns":{"list":{"args":{"1":{}},"vn":1}}};;window.VWO = window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};VWO._.ac.dNdOfst=1000;}}catch(e){_vwo_code.finish(); _vwo_code.removeLoaderAndOverlay && _vwo_code.removeLoaderAndOverlay(); var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?a=569996&s=j.php&e="+encodeURIComponent(e && e.message && e.message.substring(0,1000))+"&url"+encodeURIComponent(window.location.href)}